from tkinter import *
root = Tk()
root.title("Registration Form")
root.geometry("744x366")
label1 = Label(root,text="Registration form",font="lucida 20 bold")
label2 = Label(root,text="Full Name: ",font="lucida 10 bold")
label3 = Label(root,text="E-mail: ",font="lucida 10 bold")
label4 = Label(root,text="Gender: ",font="lucida 10 bold")
entry1 = Entry(root)
entry2 = Entry(root)
rb1 = Radiobutton(root,value=1,text="Male")
rb2 = Radiobutton(root,value=2,text="Female")
label1.pack()
label2.pack()
entry1.pack()
label3.pack()
entry2.pack()
label4.pack()
rb1.pack()
rb2.pack()
submit = Button(text="Submit").pack(pady=10)
root.mainloop()